//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSoapService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gcomputer.net/webservices/", ConfigurationName="SampleSoapService.DilbertSoap")]
    public interface DilbertSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/TodaysDilbert", ReplyAction="*")]
        System.Threading.Tasks.Task<SampleSoapService.TodaysDilbertResponse> TodaysDilbertAsync(SampleSoapService.TodaysDilbertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gcomputer.net/webservices/DailyDilbert", ReplyAction="*")]
        System.Threading.Tasks.Task<SampleSoapService.DailyDilbertResponse> DailyDilbertAsync(SampleSoapService.DailyDilbertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodaysDilbertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodaysDilbert", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public SampleSoapService.TodaysDilbertRequestBody Body;
        
        public TodaysDilbertRequest()
        {
        }
        
        public TodaysDilbertRequest(SampleSoapService.TodaysDilbertRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TodaysDilbertRequestBody
    {
        
        public TodaysDilbertRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodaysDilbertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodaysDilbertResponse", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public SampleSoapService.TodaysDilbertResponseBody Body;
        
        public TodaysDilbertResponse()
        {
        }
        
        public TodaysDilbertResponse(SampleSoapService.TodaysDilbertResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class TodaysDilbertResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TodaysDilbertResult;
        
        public TodaysDilbertResponseBody()
        {
        }
        
        public TodaysDilbertResponseBody(string TodaysDilbertResult)
        {
            this.TodaysDilbertResult = TodaysDilbertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyDilbertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyDilbert", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public SampleSoapService.DailyDilbertRequestBody Body;
        
        public DailyDilbertRequest()
        {
        }
        
        public DailyDilbertRequest(SampleSoapService.DailyDilbertRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class DailyDilbertRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime ADate;
        
        public DailyDilbertRequestBody()
        {
        }
        
        public DailyDilbertRequestBody(System.DateTime ADate)
        {
            this.ADate = ADate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyDilbertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyDilbertResponse", Namespace="http://gcomputer.net/webservices/", Order=0)]
        public SampleSoapService.DailyDilbertResponseBody Body;
        
        public DailyDilbertResponse()
        {
        }
        
        public DailyDilbertResponse(SampleSoapService.DailyDilbertResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gcomputer.net/webservices/")]
    public partial class DailyDilbertResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DailyDilbertResult;
        
        public DailyDilbertResponseBody()
        {
        }
        
        public DailyDilbertResponseBody(string DailyDilbertResult)
        {
            this.DailyDilbertResult = DailyDilbertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DilbertSoapChannel : SampleSoapService.DilbertSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DilbertSoapClient : System.ServiceModel.ClientBase<SampleSoapService.DilbertSoap>, SampleSoapService.DilbertSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DilbertSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DilbertSoapClient.GetBindingForEndpoint(endpointConfiguration), DilbertSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DilbertSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DilbertSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DilbertSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DilbertSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DilbertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SampleSoapService.TodaysDilbertResponse> SampleSoapService.DilbertSoap.TodaysDilbertAsync(SampleSoapService.TodaysDilbertRequest request)
        {
            return base.Channel.TodaysDilbertAsync(request);
        }
        
        public System.Threading.Tasks.Task<SampleSoapService.TodaysDilbertResponse> TodaysDilbertAsync()
        {
            SampleSoapService.TodaysDilbertRequest inValue = new SampleSoapService.TodaysDilbertRequest();
            inValue.Body = new SampleSoapService.TodaysDilbertRequestBody();
            return ((SampleSoapService.DilbertSoap)(this)).TodaysDilbertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SampleSoapService.DailyDilbertResponse> SampleSoapService.DilbertSoap.DailyDilbertAsync(SampleSoapService.DailyDilbertRequest request)
        {
            return base.Channel.DailyDilbertAsync(request);
        }
        
        public System.Threading.Tasks.Task<SampleSoapService.DailyDilbertResponse> DailyDilbertAsync(System.DateTime ADate)
        {
            SampleSoapService.DailyDilbertRequest inValue = new SampleSoapService.DailyDilbertRequest();
            inValue.Body = new SampleSoapService.DailyDilbertRequestBody();
            inValue.Body.ADate = ADate;
            return ((SampleSoapService.DilbertSoap)(this)).DailyDilbertAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DilbertSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DilbertSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DilbertSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.gcomputer.net/webservices/dilbert.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DilbertSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.gcomputer.net/webservices/dilbert.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DilbertSoap,
            
            DilbertSoap12,
        }
    }
}
