//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebtService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebtQueryRequest", Namespace="http://schemas.datacontract.org/2004/07/InstitutionIntegration.API.Models.Operati" +
        "ons")]
    public partial class DebtQueryRequest : object
    {
        
        private string AgreementNoField;
        
        private string SubscriberCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgreementNo
        {
            get
            {
                return this.AgreementNoField;
            }
            set
            {
                this.AgreementNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberCode
        {
            get
            {
                return this.SubscriberCodeField;
            }
            set
            {
                this.SubscriberCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/InstitutionIntegration.API.Models.Operati" +
        "ons")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DebtService.DebtQueryResponse))]
    public partial class BaseResponse : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebtQueryResponse", Namespace="http://schemas.datacontract.org/2004/07/InstitutionIntegration.API.Models.Operati" +
        "ons")]
    public partial class DebtQueryResponse : DebtService.BaseResponse
    {
        
        private DebtService.DebtQueryResponseItem[] DebtsField;
        
        private int DebtsCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DebtService.DebtQueryResponseItem[] Debts
        {
            get
            {
                return this.DebtsField;
            }
            set
            {
                this.DebtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DebtsCount
        {
            get
            {
                return this.DebtsCountField;
            }
            set
            {
                this.DebtsCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebtQueryResponseItem", Namespace="http://schemas.datacontract.org/2004/07/InstitutionIntegration.API.Models.Operati" +
        "ons")]
    public partial class DebtQueryResponseItem : object
    {
        
        private string AgreementNoField;
        
        private decimal BillAmountField;
        
        private System.DateTime BillDateField;
        
        private System.DateTime BillDueDateField;
        
        private string FullNameField;
        
        private decimal InterestAmountField;
        
        private System.Guid InvoiceNoField;
        
        private string SubscriberNoField;
        
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgreementNo
        {
            get
            {
                return this.AgreementNoField;
            }
            set
            {
                this.AgreementNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BillAmount
        {
            get
            {
                return this.BillAmountField;
            }
            set
            {
                this.BillAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDate
        {
            get
            {
                return this.BillDateField;
            }
            set
            {
                this.BillDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDueDate
        {
            get
            {
                return this.BillDueDateField;
            }
            set
            {
                this.BillDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InterestAmount
        {
            get
            {
                return this.InterestAmountField;
            }
            set
            {
                this.InterestAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriberNo
        {
            get
            {
                return this.SubscriberNoField;
            }
            set
            {
                this.SubscriberNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DebtService.IDebtService")]
    public interface IDebtService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebtService/GetDebts", ReplyAction="http://tempuri.org/IDebtService/GetDebtsResponse")]
        System.Threading.Tasks.Task<DebtService.DebtQueryResponse> GetDebtsAsync(DebtService.DebtQueryRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IDebtServiceChannel : DebtService.IDebtService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DebtServiceClient : System.ServiceModel.ClientBase<DebtService.IDebtService>, DebtService.IDebtService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DebtServiceClient() : 
                base(DebtServiceClient.GetDefaultBinding(), DebtServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDebtService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebtServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DebtServiceClient.GetBindingForEndpoint(endpointConfiguration), DebtServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebtServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DebtServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebtServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DebtServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DebtService.DebtQueryResponse> GetDebtsAsync(DebtService.DebtQueryRequest request)
        {
            return base.Channel.GetDebtsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDebtService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDebtService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.3.58/InstitutionIntegration/DebtService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DebtServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDebtService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DebtServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDebtService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDebtService,
        }
    }
}
