//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerjisaSoapService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://enerjisa.com/bank/ecd", ConfigurationName="EnerjisaSoapService.SI_ECD_OUT_SYNC")]
    public interface SI_ECD_OUT_SYNC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TahsilatResponse> TahsilatAsync(EnerjisaSoapService.TahsilatRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.BorcSorguResponse> BorcSorguAsync(EnerjisaSoapService.BorcSorguRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TalimatliAboneListesiResponse> TalimatliAboneListesiAsync(EnerjisaSoapService.TalimatliAboneListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikTalimatIptalResponse> OtomatikTalimatIptalAsync(EnerjisaSoapService.OtomatikTalimatIptalRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.GenelMutabakatResponse> GenelMutabakatAsync(EnerjisaSoapService.GenelMutabakatRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.DetayliMutabakatListeResponse> DetayliMutabakatListeAsync(EnerjisaSoapService.DetayliMutabakatListeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TahsilatTersKayitResponse> TahsilatTersKayitAsync(EnerjisaSoapService.TahsilatTersKayitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TalimatVermeResponse> TalimatVermeAsync(EnerjisaSoapService.TalimatVermeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TalimatSorguResponse> TalimatSorguAsync(EnerjisaSoapService.TalimatSorguRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikTahsilatResponse> OtomatikTahsilatAsync(EnerjisaSoapService.OtomatikTahsilatRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikOdemeListesiResponse> OtomatikOdemeListesiAsync(EnerjisaSoapService.OtomatikOdemeListesiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_PAYMENT_CREATE_NOTIFICAT", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TahsilatRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AMOUNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_PAYMENT_DOCUMENT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANCH_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTRACT_ACCOUNT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FICADOCUMENT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAYMENT_TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSTING_DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PROCESSING_DATE;
        
        public TahsilatRequest()
        {
        }
        
        public TahsilatRequest(decimal AMOUNT, string BANK_CODE, string BANK_PAYMENT_DOCUMENT_NUMBER, string BRANCH_CODE, string CONTRACT_ACCOUNT_NUMBER, string CURRENCY, string FICADOCUMENT_NUMBER, string PAYMENT_TYPE, string POSTING_DATE, decimal PROCESSING_DATE)
        {
            this.AMOUNT = AMOUNT;
            this.BANK_CODE = BANK_CODE;
            this.BANK_PAYMENT_DOCUMENT_NUMBER = BANK_PAYMENT_DOCUMENT_NUMBER;
            this.BRANCH_CODE = BRANCH_CODE;
            this.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
            this.CURRENCY = CURRENCY;
            this.FICADOCUMENT_NUMBER = FICADOCUMENT_NUMBER;
            this.PAYMENT_TYPE = PAYMENT_TYPE;
            this.POSTING_DATE = POSTING_DATE;
            this.PROCESSING_DATE = PROCESSING_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_PAYMENT_CREATE_NOTIFICAT.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TahsilatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public TahsilatResponse()
        {
        }
        
        public TahsilatResponse(string MESSAGE)
        {
            this.MESSAGE = MESSAGE;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZECD_OPENITEMS_LIST
    {
        
        private string nAMEField;
        
        private string sURNAMEField;
        
        private string cONTRACT_ACCOUNT_NUMBERField;
        
        private string fICADOCUMENT_NUMBERField;
        
        private string oPEN_ITEM_DESCRIPTIONField;
        
        private decimal aMOUNTField;
        
        private bool aMOUNTFieldSpecified;
        
        private string cURRENCYField;
        
        private string pOSTING_DATEField;
        
        private string dUE_DATEField;
        
        private string oRDER_OF_INSTALLMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SURNAME
        {
            get
            {
                return this.sURNAMEField;
            }
            set
            {
                this.sURNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONTRACT_ACCOUNT_NUMBER
        {
            get
            {
                return this.cONTRACT_ACCOUNT_NUMBERField;
            }
            set
            {
                this.cONTRACT_ACCOUNT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FICADOCUMENT_NUMBER
        {
            get
            {
                return this.fICADOCUMENT_NUMBERField;
            }
            set
            {
                this.fICADOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OPEN_ITEM_DESCRIPTION
        {
            get
            {
                return this.oPEN_ITEM_DESCRIPTIONField;
            }
            set
            {
                this.oPEN_ITEM_DESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNTSpecified
        {
            get
            {
                return this.aMOUNTFieldSpecified;
            }
            set
            {
                this.aMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string POSTING_DATE
        {
            get
            {
                return this.pOSTING_DATEField;
            }
            set
            {
                this.pOSTING_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DUE_DATE
        {
            get
            {
                return this.dUE_DATEField;
            }
            set
            {
                this.dUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ORDER_OF_INSTALLMENT
        {
            get
            {
                return this.oRDER_OF_INSTALLMENTField;
            }
            set
            {
                this.oRDER_OF_INSTALLMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZECD_AUTOMATED_PAYMENT_LIST
    {
        
        private string cONTRACT_ACCOUNT_NUMBERField;
        
        private string fICADOCUMENT_NUMBERField;
        
        private decimal aMOUNTField;
        
        private bool aMOUNTFieldSpecified;
        
        private string cURRENCYField;
        
        private string pOSTING_DATEField;
        
        private string dUE_DATEField;
        
        private string bANK_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRACT_ACCOUNT_NUMBER
        {
            get
            {
                return this.cONTRACT_ACCOUNT_NUMBERField;
            }
            set
            {
                this.cONTRACT_ACCOUNT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FICADOCUMENT_NUMBER
        {
            get
            {
                return this.fICADOCUMENT_NUMBERField;
            }
            set
            {
                this.fICADOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNTSpecified
        {
            get
            {
                return this.aMOUNTFieldSpecified;
            }
            set
            {
                this.aMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string POSTING_DATE
        {
            get
            {
                return this.pOSTING_DATEField;
            }
            set
            {
                this.pOSTING_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DUE_DATE
        {
            get
            {
                return this.dUE_DATEField;
            }
            set
            {
                this.dUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BANK_CODE
        {
            get
            {
                return this.bANK_CODEField;
            }
            set
            {
                this.bANK_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZECD_AUTO_PAYMENT_DETAILED
    {
        
        private string bANK_CODEField;
        
        private string bRANCH_CODEField;
        
        private string cONTRACT_ACCOUNT_NUMBERField;
        
        private string sTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BANK_CODE
        {
            get
            {
                return this.bANK_CODEField;
            }
            set
            {
                this.bANK_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BRANCH_CODE
        {
            get
            {
                return this.bRANCH_CODEField;
            }
            set
            {
                this.bRANCH_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONTRACT_ACCOUNT_NUMBER
        {
            get
            {
                return this.cONTRACT_ACCOUNT_NUMBERField;
            }
            set
            {
                this.cONTRACT_ACCOUNT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZECD_COLLECTION_ORDER_CHECK
    {
        
        private string nAMEField;
        
        private string sURNAMEField;
        
        private string cONTRACT_ACCOUNT_NUMBERField;
        
        private string aDDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SURNAME
        {
            get
            {
                return this.sURNAMEField;
            }
            set
            {
                this.sURNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONTRACT_ACCOUNT_NUMBER
        {
            get
            {
                return this.cONTRACT_ACCOUNT_NUMBERField;
            }
            set
            {
                this.cONTRACT_ACCOUNT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ADDRESS
        {
            get
            {
                return this.aDDRESSField;
            }
            set
            {
                this.aDDRESSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZECD_DETAILED_RECONCILIATION
    {
        
        private string bANK_CODEField;
        
        private string bRANCH_CODEField;
        
        private string pOSTING_DATEField;
        
        private string cONTRACT_ACCOUNT_NUMBERField;
        
        private string bANK_PAYMENT_DOCUMENT_NUMBERField;
        
        private string fICADOCUMENT_NUMBERField;
        
        private decimal aMOUNTField;
        
        private bool aMOUNTFieldSpecified;
        
        private string cURRENCYField;
        
        private string sTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BANK_CODE
        {
            get
            {
                return this.bANK_CODEField;
            }
            set
            {
                this.bANK_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BRANCH_CODE
        {
            get
            {
                return this.bRANCH_CODEField;
            }
            set
            {
                this.bRANCH_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string POSTING_DATE
        {
            get
            {
                return this.pOSTING_DATEField;
            }
            set
            {
                this.pOSTING_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONTRACT_ACCOUNT_NUMBER
        {
            get
            {
                return this.cONTRACT_ACCOUNT_NUMBERField;
            }
            set
            {
                this.cONTRACT_ACCOUNT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BANK_PAYMENT_DOCUMENT_NUMBER
        {
            get
            {
                return this.bANK_PAYMENT_DOCUMENT_NUMBERField;
            }
            set
            {
                this.bANK_PAYMENT_DOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FICADOCUMENT_NUMBER
        {
            get
            {
                return this.fICADOCUMENT_NUMBERField;
            }
            set
            {
                this.fICADOCUMENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNTSpecified
        {
            get
            {
                return this.aMOUNTFieldSpecified;
            }
            set
            {
                this.aMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZECD_GLOBAL_RECONCILIATION
    {
        
        private string bANK_CODEField;
        
        private string bRANCH_CODEField;
        
        private string rECONCILIATION_DATEField;
        
        private string tOTAL_TRANSACTION_COUNTField;
        
        private string tOTAL_CANCELLED_TRANSACTION_COField;
        
        private decimal tOTAL_TRANSACTION_AMOUNTField;
        
        private bool tOTAL_TRANSACTION_AMOUNTFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BANK_CODE
        {
            get
            {
                return this.bANK_CODEField;
            }
            set
            {
                this.bANK_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BRANCH_CODE
        {
            get
            {
                return this.bRANCH_CODEField;
            }
            set
            {
                this.bRANCH_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RECONCILIATION_DATE
        {
            get
            {
                return this.rECONCILIATION_DATEField;
            }
            set
            {
                this.rECONCILIATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string TOTAL_TRANSACTION_COUNT
        {
            get
            {
                return this.tOTAL_TRANSACTION_COUNTField;
            }
            set
            {
                this.tOTAL_TRANSACTION_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string TOTAL_CANCELLED_TRANSACTION_CO
        {
            get
            {
                return this.tOTAL_CANCELLED_TRANSACTION_COField;
            }
            set
            {
                this.tOTAL_CANCELLED_TRANSACTION_COField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal TOTAL_TRANSACTION_AMOUNT
        {
            get
            {
                return this.tOTAL_TRANSACTION_AMOUNTField;
            }
            set
            {
                this.tOTAL_TRANSACTION_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOTAL_TRANSACTION_AMOUNTSpecified
        {
            get
            {
                return this.tOTAL_TRANSACTION_AMOUNTFieldSpecified;
            }
            set
            {
                this.tOTAL_TRANSACTION_AMOUNTFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_OPEN_ITEM_LIST", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class BorcSorguRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTRACT_ACCOUNT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCUMENT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LEGACY_CONTRACT_ACCOUNT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRIDNUMBER;
        
        public BorcSorguRequest()
        {
        }
        
        public BorcSorguRequest(string CONTRACT_ACCOUNT_NUMBER, string DOCUMENT_NUMBER, string LEGACY_CONTRACT_ACCOUNT_NUMBER, string TRIDNUMBER)
        {
            this.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
            this.DOCUMENT_NUMBER = DOCUMENT_NUMBER;
            this.LEGACY_CONTRACT_ACCOUNT_NUMBER = LEGACY_CONTRACT_ACCOUNT_NUMBER;
            this.TRIDNUMBER = TRIDNUMBER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_OPEN_ITEM_LIST.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class BorcSorguResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EnerjisaSoapService.ZECD_OPENITEMS_LIST[] ITEM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public BorcSorguResponse()
        {
        }
        
        public BorcSorguResponse(EnerjisaSoapService.ZECD_OPENITEMS_LIST[] ITEM, string MESSAGE)
        {
            this.ITEM = ITEM;
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_LIST", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TalimatliAboneListesiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATE;
        
        public TalimatliAboneListesiRequest()
        {
        }
        
        public TalimatliAboneListesiRequest(string BANK_CODE, string DATE)
        {
            this.BANK_CODE = BANK_CODE;
            this.DATE = DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_LIST.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TalimatliAboneListesiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string CANCELED_COLLECTION_ORDER_COUN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string NEW_CREATED_COLLECTION_ORDER_C;
        
        public TalimatliAboneListesiResponse()
        {
        }
        
        public TalimatliAboneListesiResponse(string CANCELED_COLLECTION_ORDER_COUN, string MESSAGE, string NEW_CREATED_COLLECTION_ORDER_C)
        {
            this.CANCELED_COLLECTION_ORDER_COUN = CANCELED_COLLECTION_ORDER_COUN;
            this.MESSAGE = MESSAGE;
            this.NEW_CREATED_COLLECTION_ORDER_C = NEW_CREATED_COLLECTION_ORDER_C;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_CANCEL", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class OtomatikTalimatIptalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTRACT_ACCOUNT_NUMBER;
        
        public OtomatikTalimatIptalRequest()
        {
        }
        
        public OtomatikTalimatIptalRequest(string BANK_CODE, string CONTRACT_ACCOUNT_NUMBER)
        {
            this.BANK_CODE = BANK_CODE;
            this.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_CANCEL.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class OtomatikTalimatIptalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public OtomatikTalimatIptalResponse()
        {
        }
        
        public OtomatikTalimatIptalResponse(string MESSAGE)
        {
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_GLOBAL_RECONCILIATION", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class GenelMutabakatRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECONCILIATION_DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string TOTAL_CANCELLED_TRANSACTION_CO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TOTAL_TRANSACTION_AMOUNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string TOTAL_TRANSACTION_COUNT;
        
        public GenelMutabakatRequest()
        {
        }
        
        public GenelMutabakatRequest(string BANK_CODE, string RECONCILIATION_DATE, string TOTAL_CANCELLED_TRANSACTION_CO, decimal TOTAL_TRANSACTION_AMOUNT, string TOTAL_TRANSACTION_COUNT)
        {
            this.BANK_CODE = BANK_CODE;
            this.RECONCILIATION_DATE = RECONCILIATION_DATE;
            this.TOTAL_CANCELLED_TRANSACTION_CO = TOTAL_CANCELLED_TRANSACTION_CO;
            this.TOTAL_TRANSACTION_AMOUNT = TOTAL_TRANSACTION_AMOUNT;
            this.TOTAL_TRANSACTION_COUNT = TOTAL_TRANSACTION_COUNT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_GLOBAL_RECONCILIATION.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class GenelMutabakatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EnerjisaSoapService.ZECD_GLOBAL_RECONCILIATION[] ITEM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public GenelMutabakatResponse()
        {
        }
        
        public GenelMutabakatResponse(EnerjisaSoapService.ZECD_GLOBAL_RECONCILIATION[] ITEM, string MESSAGE)
        {
            this.ITEM = ITEM;
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_DETAILED_RECONCILIATION", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class DetayliMutabakatListeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANCH_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECONCILIATION_DATE;
        
        public DetayliMutabakatListeRequest()
        {
        }
        
        public DetayliMutabakatListeRequest(string BANK_CODE, string BRANCH_CODE, string RECONCILIATION_DATE)
        {
            this.BANK_CODE = BANK_CODE;
            this.BRANCH_CODE = BRANCH_CODE;
            this.RECONCILIATION_DATE = RECONCILIATION_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_DETAILED_RECONCILIATION.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class DetayliMutabakatListeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EnerjisaSoapService.ZECD_DETAILED_RECONCILIATION[] ITEM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public DetayliMutabakatListeResponse()
        {
        }
        
        public DetayliMutabakatListeResponse(EnerjisaSoapService.ZECD_DETAILED_RECONCILIATION[] ITEM, string MESSAGE)
        {
            this.ITEM = ITEM;
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_PAYMENT_REVERSE_NOTIFCTN", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TahsilatTersKayitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_PAYMENT_DOCUMENT_NUMBER;
        
        public TahsilatTersKayitRequest()
        {
        }
        
        public TahsilatTersKayitRequest(string BANK_CODE, string BANK_PAYMENT_DOCUMENT_NUMBER)
        {
            this.BANK_CODE = BANK_CODE;
            this.BANK_PAYMENT_DOCUMENT_NUMBER = BANK_PAYMENT_DOCUMENT_NUMBER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_PAYMENT_REVERSE_NOTIFCTN.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TahsilatTersKayitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public TahsilatTersKayitResponse()
        {
        }
        
        public TahsilatTersKayitResponse(string MESSAGE)
        {
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_CREATE", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TalimatVermeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANCH_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTRACT_ACCOUNT_NUMBER;
        
        public TalimatVermeRequest()
        {
        }
        
        public TalimatVermeRequest(string BANK_CODE, string BRANCH_CODE, string CONTRACT_ACCOUNT_NUMBER)
        {
            this.BANK_CODE = BANK_CODE;
            this.BRANCH_CODE = BRANCH_CODE;
            this.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_CREATE.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TalimatVermeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public TalimatVermeResponse()
        {
        }
        
        public TalimatVermeResponse(string MESSAGE)
        {
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_CHECK", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TalimatSorguRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTRACT_ACCOUNT_NUMBER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LEGACY_CONTRACT_ACCOUNT_NUMBER;
        
        public TalimatSorguRequest()
        {
        }
        
        public TalimatSorguRequest(string CONTRACT_ACCOUNT_NUMBER, string LEGACY_CONTRACT_ACCOUNT_NUMBER)
        {
            this.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
            this.LEGACY_CONTRACT_ACCOUNT_NUMBER = LEGACY_CONTRACT_ACCOUNT_NUMBER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_COLLECTION_ORDER_CHECK.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class TalimatSorguResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnerjisaSoapService.ZECD_COLLECTION_ORDER_CHECK OUTPUT;
        
        public TalimatSorguResponse()
        {
        }
        
        public TalimatSorguResponse(string MESSAGE, EnerjisaSoapService.ZECD_COLLECTION_ORDER_CHECK OUTPUT)
        {
            this.MESSAGE = MESSAGE;
            this.OUTPUT = OUTPUT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_AUTO_PAYMENT_DETAILED", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class OtomatikTahsilatRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECONCILIATION_DATE;
        
        public OtomatikTahsilatRequest()
        {
        }
        
        public OtomatikTahsilatRequest(string BANK_CODE, string RECONCILIATION_DATE)
        {
            this.BANK_CODE = BANK_CODE;
            this.RECONCILIATION_DATE = RECONCILIATION_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_AUTO_PAYMENT_DETAILED.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class OtomatikTahsilatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EnerjisaSoapService.ZECD_AUTO_PAYMENT_DETAILED[] ITEM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public OtomatikTahsilatResponse()
        {
        }
        
        public OtomatikTahsilatResponse(EnerjisaSoapService.ZECD_AUTO_PAYMENT_DETAILED[] ITEM, string MESSAGE)
        {
            this.ITEM = ITEM;
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_AUTOMATED_PAYMENT_LIST", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class OtomatikOdemeListesiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUE_DATE;
        
        public OtomatikOdemeListesiRequest()
        {
        }
        
        public OtomatikOdemeListesiRequest(string BANK_CODE, string DUE_DATE)
        {
            this.BANK_CODE = BANK_CODE;
            this.DUE_DATE = DUE_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z_ECD_AUTOMATED_PAYMENT_LIST.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class OtomatikOdemeListesiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EnerjisaSoapService.ZECD_AUTOMATED_PAYMENT_LIST[] ITEM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        public OtomatikOdemeListesiResponse()
        {
        }
        
        public OtomatikOdemeListesiResponse(EnerjisaSoapService.ZECD_AUTOMATED_PAYMENT_LIST[] ITEM, string MESSAGE)
        {
            this.ITEM = ITEM;
            this.MESSAGE = MESSAGE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SI_ECD_OUT_SYNCChannel : EnerjisaSoapService.SI_ECD_OUT_SYNC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SI_ECD_OUT_SYNCClient : System.ServiceModel.ClientBase<EnerjisaSoapService.SI_ECD_OUT_SYNC>, EnerjisaSoapService.SI_ECD_OUT_SYNC
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_ECD_OUT_SYNCClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_ECD_OUT_SYNCClient.GetBindingForEndpoint(endpointConfiguration), SI_ECD_OUT_SYNCClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_ECD_OUT_SYNCClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_ECD_OUT_SYNCClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_ECD_OUT_SYNCClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_ECD_OUT_SYNCClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_ECD_OUT_SYNCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TahsilatResponse> EnerjisaSoapService.SI_ECD_OUT_SYNC.TahsilatAsync(EnerjisaSoapService.TahsilatRequest request)
        {
            return base.Channel.TahsilatAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.TahsilatResponse> TahsilatAsync(decimal AMOUNT, string BANK_CODE, string BANK_PAYMENT_DOCUMENT_NUMBER, string BRANCH_CODE, string CONTRACT_ACCOUNT_NUMBER, string CURRENCY, string FICADOCUMENT_NUMBER, string PAYMENT_TYPE, string POSTING_DATE, decimal PROCESSING_DATE)
        {
            EnerjisaSoapService.TahsilatRequest inValue = new EnerjisaSoapService.TahsilatRequest();
            inValue.AMOUNT = AMOUNT;
            inValue.BANK_CODE = BANK_CODE;
            inValue.BANK_PAYMENT_DOCUMENT_NUMBER = BANK_PAYMENT_DOCUMENT_NUMBER;
            inValue.BRANCH_CODE = BRANCH_CODE;
            inValue.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
            inValue.CURRENCY = CURRENCY;
            inValue.FICADOCUMENT_NUMBER = FICADOCUMENT_NUMBER;
            inValue.PAYMENT_TYPE = PAYMENT_TYPE;
            inValue.POSTING_DATE = POSTING_DATE;
            inValue.PROCESSING_DATE = PROCESSING_DATE;
            return ((EnerjisaSoapService.SI_ECD_OUT_SYNC)(this)).TahsilatAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.BorcSorguResponse> BorcSorguAsync(EnerjisaSoapService.BorcSorguRequest request)
        {
            return base.Channel.BorcSorguAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.TalimatliAboneListesiResponse> TalimatliAboneListesiAsync(EnerjisaSoapService.TalimatliAboneListesiRequest request)
        {
            return base.Channel.TalimatliAboneListesiAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikTalimatIptalResponse> EnerjisaSoapService.SI_ECD_OUT_SYNC.OtomatikTalimatIptalAsync(EnerjisaSoapService.OtomatikTalimatIptalRequest request)
        {
            return base.Channel.OtomatikTalimatIptalAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikTalimatIptalResponse> OtomatikTalimatIptalAsync(string BANK_CODE, string CONTRACT_ACCOUNT_NUMBER)
        {
            EnerjisaSoapService.OtomatikTalimatIptalRequest inValue = new EnerjisaSoapService.OtomatikTalimatIptalRequest();
            inValue.BANK_CODE = BANK_CODE;
            inValue.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
            return ((EnerjisaSoapService.SI_ECD_OUT_SYNC)(this)).OtomatikTalimatIptalAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.GenelMutabakatResponse> GenelMutabakatAsync(EnerjisaSoapService.GenelMutabakatRequest request)
        {
            return base.Channel.GenelMutabakatAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.DetayliMutabakatListeResponse> DetayliMutabakatListeAsync(EnerjisaSoapService.DetayliMutabakatListeRequest request)
        {
            return base.Channel.DetayliMutabakatListeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TahsilatTersKayitResponse> EnerjisaSoapService.SI_ECD_OUT_SYNC.TahsilatTersKayitAsync(EnerjisaSoapService.TahsilatTersKayitRequest request)
        {
            return base.Channel.TahsilatTersKayitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.TahsilatTersKayitResponse> TahsilatTersKayitAsync(string BANK_CODE, string BANK_PAYMENT_DOCUMENT_NUMBER)
        {
            EnerjisaSoapService.TahsilatTersKayitRequest inValue = new EnerjisaSoapService.TahsilatTersKayitRequest();
            inValue.BANK_CODE = BANK_CODE;
            inValue.BANK_PAYMENT_DOCUMENT_NUMBER = BANK_PAYMENT_DOCUMENT_NUMBER;
            return ((EnerjisaSoapService.SI_ECD_OUT_SYNC)(this)).TahsilatTersKayitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnerjisaSoapService.TalimatVermeResponse> EnerjisaSoapService.SI_ECD_OUT_SYNC.TalimatVermeAsync(EnerjisaSoapService.TalimatVermeRequest request)
        {
            return base.Channel.TalimatVermeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.TalimatVermeResponse> TalimatVermeAsync(string BANK_CODE, string BRANCH_CODE, string CONTRACT_ACCOUNT_NUMBER)
        {
            EnerjisaSoapService.TalimatVermeRequest inValue = new EnerjisaSoapService.TalimatVermeRequest();
            inValue.BANK_CODE = BANK_CODE;
            inValue.BRANCH_CODE = BRANCH_CODE;
            inValue.CONTRACT_ACCOUNT_NUMBER = CONTRACT_ACCOUNT_NUMBER;
            return ((EnerjisaSoapService.SI_ECD_OUT_SYNC)(this)).TalimatVermeAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.TalimatSorguResponse> TalimatSorguAsync(EnerjisaSoapService.TalimatSorguRequest request)
        {
            return base.Channel.TalimatSorguAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikTahsilatResponse> OtomatikTahsilatAsync(EnerjisaSoapService.OtomatikTahsilatRequest request)
        {
            return base.Channel.OtomatikTahsilatAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnerjisaSoapService.OtomatikOdemeListesiResponse> OtomatikOdemeListesiAsync(EnerjisaSoapService.OtomatikOdemeListesiRequest request)
        {
            return base.Channel.OtomatikOdemeListesiAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://intq.eedas.com.tr/XISOAPAdapter/MessageServlet?senderParty=PY_BASKENT_EDA" +
                        "S&senderService=BC_SEKERBANK&receiverParty=&receiverService=&interface=SI_ECD_OU" +
                        "T_SYNC&interfaceNamespace=http%3A%2F%2Fenerjisa.com%2Fbank%2Fecd");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://intq-cc.eedas.com.tr/XISOAPAdapter/MessageServlet?senderParty=PY_BASKENT_" +
                        "EDAS&senderService=BC_SEKERBANK&receiverParty=&receiverService=&interface=SI_ECD" +
                        "_OUT_SYNC&interfaceNamespace=http%3A%2F%2Fenerjisa.com%2Fbank%2Fecd");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
